CREATE TABLE `NOTIFICATION`(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `notifier` BIGINT NOT NULL,
  `receiver` BIGINT NOT NULL,
  `outerId` BIGINT NOT NULL,
  `type` INT NOT NULL,
  `gmt_create` BIGINT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `notifier_name` VARCHAR(100) DEFAULT NULL,
  `outer_title` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
